import type { SpotifyApi } from '../../../../../src/conductor/providers/spotify/types/typed';

export const spotifySinglePlaylistResponse: SpotifyApi.SinglePlaylistResponse =
  {
    collaborative: false,
    description: 'Sample playlist description',
    external_urls: { spotify: 'https://open.spotify.com/playlist/sample' },
    followers: { href: null, total: 1000 },
    href: 'https://api.spotify.com/v1/playlists/sample',
    id: 'sample',
    images: [
      { height: 640, url: 'https://example.com/image1.jpg', width: 640 },
      { height: 300, url: 'https://example.com/image2.jpg', width: 300 },
      { height: 64, url: 'https://example.com/image3.jpg', width: 64 },
    ],
    name: 'Sample Playlist',
    owner: {
      display_name: 'Sample User',
      external_urls: { spotify: 'https://open.spotify.com/user/sample' },
      href: 'https://api.spotify.com/v1/users/sample',
      id: 'sample',
      type: 'user',
      uri: 'spotify:user:sample',
    },
    public: true,
    snapshot_id: 'sample_snapshot_id',
    tracks: {
      href: 'https://api.spotify.com/v1/playlists/sample/tracks',
      items: [
        {
          added_at: '2023-01-01T00:00:00Z',
          added_by: {
            external_urls: { spotify: 'https://open.spotify.com/user/sample' },
            href: 'https://api.spotify.com/v1/users/sample',
            id: 'sample',
            type: 'user',
            uri: 'spotify:user:sample',
          },
          is_local: false,
          track: {
            external_ids: {
              isrc: 'sample_isrc',
              ean: 'sample_ean',
              upc: 'sample_upc',
            },
            album: {
              album_type: 'album',
              artists: [
                {
                  external_urls: {
                    spotify: 'https://open.spotify.com/artist/sample',
                  },
                  href: 'https://api.spotify.com/v1/artists/sample',
                  id: 'sample',
                  name: 'Sample Artist',
                  type: 'artist',
                  uri: 'spotify:artist:sample',
                },
              ],
              available_markets: ['US', 'CA'],
              href: 'https://api.spotify.com/v1/albums/sample',
              id: 'sample',
              images: [
                {
                  height: 640,
                  url: 'https://example.com/album_image1.jpg',
                  width: 640,
                },
                {
                  height: 300,
                  url: 'https://example.com/album_image2.jpg',
                  width: 300,
                },
                {
                  height: 64,
                  url: 'https://example.com/album_image3.jpg',
                  width: 64,
                },
              ],
              name: 'Sample Album',
              release_date: '2023-01-01',
              release_date_precision: 'day',
              total_tracks: 10,
              type: 'album',
              uri: 'spotify:album:sample',
              external_urls: {
                spotify: 'https://open.spotify.com/album/sample',
              },
            },
            artists: [
              {
                external_urls: {
                  spotify: 'https://open.spotify.com/artist/sample',
                },
                href: 'https://api.spotify.com/v1/artists/sample',
                id: 'sample',
                name: 'Sample Artist',
                type: 'artist',
                uri: 'spotify:artist:sample',
              },
            ],
            available_markets: ['US', 'CA'],
            disc_number: 1,
            duration_ms: 200000,
            explicit: false,
            external_urls: { spotify: 'https://open.spotify.com/track/sample' },
            href: 'https://api.spotify.com/v1/tracks/sample',
            id: 'sample',
            is_playable: true,
            name: 'Sample Track',
            popularity: 80,
            preview_url: 'https://example.com/track_preview.mp3',
            track_number: 1,
            type: 'track',
            uri: 'spotify:track:sample',
          },
        },
      ],
      limit: 20,
      next: null,
      offset: 0,
      previous: null,
      total: 1,
    },
    type: 'playlist',
    uri: 'spotify:playlist:sample',
  };

export const spotifyPlaylistSnapshotResponse: SpotifyApi.PlaylistSnapshotResponse =
  {
    snapshot_id: 'sample_snapshot_id',
  };

export const spotifyListOfCurrentUsersPlaylistsResponse: SpotifyApi.ListOfCurrentUsersPlaylistsResponse =
  {
    href: 'https://api.spotify.com/v1/me/playlists',
    items: [
      {
        collaborative: false,
        description: 'Sample playlist description',
        external_urls: { spotify: 'https://open.spotify.com/playlist/sample' },
        href: 'https://api.spotify.com/v1/playlists/sample',
        id: 'sample',
        images: [
          { height: 640, url: 'https://example.com/image1.jpg', width: 640 },
        ],
        name: 'Sample Playlist',
        owner: {
          display_name: 'Sample User',
          external_urls: { spotify: 'https://open.spotify.com/user/sample' },
          href: 'https://api.spotify.com/v1/users/sample',
          id: 'sample',
          type: 'user',
          uri: 'spotify:user:sample',
        },
        public: true,
        snapshot_id: 'sample_snapshot_id',
        tracks: {
          href: 'https://api.spotify.com/v1/playlists/sample/tracks',
          total: 10,
        },
        type: 'playlist',
        uri: 'spotify:playlist:sample',
      },
    ],
    limit: 20,
    next: null,
    offset: 0,
    previous: null,
    total: 1,
  };

export const spotifyListOfUsersPlaylistsResponse: SpotifyApi.ListOfUsersPlaylistsResponse =
  {
    href: 'https://api.spotify.com/v1/users/sample/playlists',
    items: [
      {
        collaborative: false,
        description: 'Sample playlist description',
        external_urls: { spotify: 'https://open.spotify.com/playlist/sample' },
        href: 'https://api.spotify.com/v1/playlists/sample',
        id: 'sample',
        images: [
          { height: 640, url: 'https://example.com/image1.jpg', width: 640 },
        ],
        name: 'Sample Playlist',
        owner: {
          display_name: 'Sample User',
          external_urls: { spotify: 'https://open.spotify.com/user/sample' },
          href: 'https://api.spotify.com/v1/users/sample',
          id: 'sample',
          type: 'user',
          uri: 'spotify:user:sample',
        },
        public: true,
        snapshot_id: 'sample_snapshot_id',
        tracks: {
          href: 'https://api.spotify.com/v1/playlists/sample/tracks',
          total: 10,
        },
        type: 'playlist',
        uri: 'spotify:playlist:sample',
      },
    ],
    limit: 20,
    next: null,
    offset: 0,
    previous: null,
    total: 1,
  };

export const spotifyCreatePlaylistResponse: SpotifyApi.CreatePlaylistResponse =
  {
    collaborative: false,
    description: 'Sample playlist description',
    external_urls: { spotify: 'https://open.spotify.com/playlist/sample' },
    followers: { href: null, total: 1000 },
    href: 'https://api.spotify.com/v1/playlists/sample',
    id: 'sample',
    images: [
      { height: 640, url: 'https://example.com/image1.jpg', width: 640 },
    ],
    name: 'Sample Playlist',
    owner: {
      display_name: 'Sample User',
      external_urls: { spotify: 'https://open.spotify.com/user/sample' },
      href: 'https://api.spotify.com/v1/users/sample',
      id: 'sample',
      type: 'user',
      uri: 'spotify:user:sample',
    },
    public: true,
    snapshot_id: 'sample_snapshot_id',
    tracks: {
      href: 'https://api.spotify.com/v1/playlists/sample/tracks',
      total: 10,
      offset: 0,
      limit: 20,
      next: null,
      previous: null,
      items: [
        {
          added_at: '2023-01-01T00:00:00Z',
          added_by: {
            external_urls: {
              spotify: 'https://open.spotify.com/user/sample',
            },
            href: 'https://api.spotify.com/v1/users/sample',
            id: 'sample',
            type: 'user',
            uri: 'spotify:user:sample',
          },
          is_local: false,
          track: {
            album: {
              album_type: 'album',
              artists: [
                {
                  external_urls: {
                    spotify: 'https://open.spotify.com/artist/sample',
                  },
                  href: 'https://api.spotify.com/v1/artists/sample',
                  id: 'sample',
                  name: 'Sample Artist',
                  type: 'artist',
                  uri: 'spotify:artist:sample',
                },
              ],
              available_markets: ['US', 'CA'],
              href: 'https://api.spotify.com/v1/albums/sample',
              id: 'sample',
              images: [
                {
                  height: 640,
                  url: 'https://example.com/album_image1.jpg',
                  width: 640,
                },
              ],
              name: 'Sample Album',
              release_date: '2023-01-01',
              release_date_precision: 'day',
              total_tracks: 10,
              type: 'album',
              uri: 'spotify:album:sample',
              external_urls: {
                spotify: 'https://open.spotify.com/album/sample',
              },
            },
            artists: [
              {
                external_urls: {
                  spotify: 'https://open.spotify.com/artist/sample',
                },
                href: 'https://api.spotify.com/v1/artists/sample',
                id: 'sample',
                name: 'Sample Artist',
                type: 'artist',
                uri: 'spotify:artist:sample',
              },
            ],
            available_markets: ['US', 'CA'],
            disc_number: 1,
            duration_ms: 200000,
            explicit: false,
            external_urls: {
              spotify: 'https://open.spotify.com/track/sample',
            },
            href: 'https://api.spotify.com/v1/tracks/sample',
            id: 'sample',
            is_playable: true,
            name: 'Sample Track',
            popularity: 80,
            preview_url: 'https://example.com/track_preview.mp3',
            track_number: 1,
            type: 'track',
            uri: 'spotify:track:sample',
            external_ids: {
              isrc: 'sample_isrc',
              ean: 'sample_ean',
              upc: 'sample_upc',
            },
          },
        },
      ],
    },
    type: 'playlist',
    uri: 'spotify:playlist:sample',
  };

export const spotifyGetItemsOfPlaylistResponse: SpotifyApi.PlaylistTrackResponse =
  {
    href: 'https://api.spotify.com/v1/playlists/3cEYpjA9oz9GiPac4AsH4n/tracks?offset=0&limit=100&locale=de-DE,de;q%3D0.9,en-US;q%3D0.8,en;q%3D0.7',
    items: [
      {
        added_at: '2015-01-15T12:39:22Z',
        added_by: {
          external_urls: {
            spotify: 'https://open.spotify.com/user/jmperezperez',
          },
          href: 'https://api.spotify.com/v1/users/jmperezperez',
          id: 'jmperezperez',
          type: 'user',
          uri: 'spotify:user:jmperezperez',
        },
        is_local: false,

        track: {
          preview_url:
            'https://p.scdn.co/mp3-preview/04599a1fe12ffac01d2bcb08340f84c0dd2cc335?cid=cfe923b2d660439caf2b557b21f31221',
          available_markets: [
            'AR',
            'AU',
            'AT',
            'BE',
            'BO',
            'BR',
            'BG',
            'CA',
            'CL',
            'CO',
            'CR',
            'CY',
            'CZ',
            'DK',
            'DO',
            'DE',
            'EC',
            'EE',
            'SV',
            'FI',
            'FR',
            'GR',
            'GT',
            'HN',
            'HK',
            'HU',
            'IS',
            'IE',
            'IT',
            'LV',
            'LT',
            'LU',
            'MY',
            'MT',
            'MX',
            'NL',
            'NZ',
            'NI',
            'NO',
            'PA',
            'PY',
            'PE',
            'PH',
            'PL',
            'PT',
            'SG',
            'SK',
            'ES',
            'SE',
            'CH',
            'TW',
            'TR',
            'UY',
            'US',
            'GB',
            'AD',
            'LI',
            'MC',
            'ID',
            'JP',
            'TH',
            'VN',
            'RO',
            'IL',
            'ZA',
            'SA',
            'AE',
            'BH',
            'QA',
            'OM',
            'KW',
            'EG',
            'MA',
            'DZ',
            'TN',
            'LB',
            'JO',
            'PS',
            'IN',
            'BY',
            'KZ',
            'MD',
            'UA',
            'AL',
            'BA',
            'HR',
            'ME',
            'MK',
            'RS',
            'SI',
            'KR',
            'BD',
            'PK',
            'LK',
            'GH',
            'KE',
            'NG',
            'TZ',
            'UG',
            'AG',
            'AM',
            'BS',
            'BB',
            'BZ',
            'BT',
            'BW',
            'BF',
            'CV',
            'CW',
            'DM',
            'FJ',
            'GM',
            'GE',
            'GD',
            'GW',
            'GY',
            'HT',
            'JM',
            'KI',
            'LS',
            'LR',
            'MW',
            'MV',
            'ML',
            'MH',
            'FM',
            'NA',
            'NR',
            'NE',
            'PW',
            'PG',
            'PR',
            'WS',
            'SM',
            'ST',
            'SN',
            'SC',
            'SL',
            'SB',
            'KN',
            'LC',
            'VC',
            'SR',
            'TL',
            'TO',
            'TT',
            'TV',
            'VU',
            'AZ',
            'BN',
            'BI',
            'KH',
            'CM',
            'TD',
            'KM',
            'GQ',
            'SZ',
            'GA',
            'GN',
            'KG',
            'LA',
            'MO',
            'MR',
            'MN',
            'NP',
            'RW',
            'TG',
            'UZ',
            'ZW',
            'BJ',
            'MG',
            'MU',
            'MZ',
            'AO',
            'CI',
            'DJ',
            'ZM',
            'CD',
            'CG',
            'IQ',
            'LY',
            'TJ',
            'VE',
            'ET',
            'XK',
          ],
          explicit: false,
          type: 'track',

          album: {
            available_markets: [
              'AR',
              'AU',
              'AT',
              'BE',
              'BO',
              'BR',
              'BG',
              'CA',
              'CL',
              'CO',
              'CR',
              'CY',
              'CZ',
              'DK',
              'DO',
              'DE',
              'EC',
              'EE',
              'SV',
              'FI',
              'FR',
              'GR',
              'GT',
              'HN',
              'HK',
              'HU',
              'IS',
              'IE',
              'IT',
              'LV',
              'LT',
              'LU',
              'MY',
              'MT',
              'MX',
              'NL',
              'NZ',
              'NI',
              'NO',
              'PA',
              'PY',
              'PE',
              'PH',
              'PL',
              'PT',
              'SG',
              'SK',
              'ES',
              'SE',
              'CH',
              'TW',
              'TR',
              'UY',
              'US',
              'GB',
              'AD',
              'LI',
              'MC',
              'ID',
              'JP',
              'TH',
              'VN',
              'RO',
              'IL',
              'ZA',
              'SA',
              'AE',
              'BH',
              'QA',
              'OM',
              'KW',
              'EG',
              'MA',
              'DZ',
              'TN',
              'LB',
              'JO',
              'PS',
              'IN',
              'BY',
              'KZ',
              'MD',
              'UA',
              'AL',
              'BA',
              'HR',
              'ME',
              'MK',
              'RS',
              'SI',
              'KR',
              'BD',
              'PK',
              'LK',
              'GH',
              'KE',
              'NG',
              'TZ',
              'UG',
              'AG',
              'AM',
              'BS',
              'BB',
              'BZ',
              'BT',
              'BW',
              'BF',
              'CV',
              'CW',
              'DM',
              'FJ',
              'GM',
              'GE',
              'GD',
              'GW',
              'GY',
              'HT',
              'JM',
              'KI',
              'LS',
              'LR',
              'MW',
              'MV',
              'ML',
              'MH',
              'FM',
              'NA',
              'NR',
              'NE',
              'PW',
              'PG',
              'PR',
              'WS',
              'SM',
              'ST',
              'SN',
              'SC',
              'SL',
              'SB',
              'KN',
              'LC',
              'VC',
              'SR',
              'TL',
              'TO',
              'TT',
              'TV',
              'VU',
              'AZ',
              'BN',
              'BI',
              'KH',
              'CM',
              'TD',
              'KM',
              'GQ',
              'SZ',
              'GA',
              'GN',
              'KG',
              'LA',
              'MO',
              'MR',
              'MN',
              'NP',
              'RW',
              'TG',
              'UZ',
              'ZW',
              'BJ',
              'MG',
              'MU',
              'MZ',
              'AO',
              'CI',
              'DJ',
              'ZM',
              'CD',
              'CG',
              'IQ',
              'LY',
              'TJ',
              'VE',
              'ET',
              'XK',
            ],
            type: 'album',
            album_type: 'compilation',
            href: 'https://api.spotify.com/v1/albums/2pANdqPvxInB0YvcDiw4ko',
            id: '2pANdqPvxInB0YvcDiw4ko',
            images: [
              {
                height: 640,
                url: 'https://i.scdn.co/image/ab67616d0000b273ce6d0eef0c1ce77e5f95bbbc',
                width: 640,
              },
              {
                height: 300,
                url: 'https://i.scdn.co/image/ab67616d00001e02ce6d0eef0c1ce77e5f95bbbc',
                width: 300,
              },
              {
                height: 64,
                url: 'https://i.scdn.co/image/ab67616d00004851ce6d0eef0c1ce77e5f95bbbc',
                width: 64,
              },
            ],
            name: 'Progressive Psy Trance Picks Vol.8',
            release_date: '2012-04-02',
            release_date_precision: 'day',
            uri: 'spotify:album:2pANdqPvxInB0YvcDiw4ko',
            artists: [
              {
                external_urls: {
                  spotify:
                    'https://open.spotify.com/artist/0LyfQWJT6nXafLPZqxe9Of',
                },
                href: 'https://api.spotify.com/v1/artists/0LyfQWJT6nXafLPZqxe9Of',
                id: '0LyfQWJT6nXafLPZqxe9Of',
                name: 'Verschiedene Interpreten',
                type: 'artist',
                uri: 'spotify:artist:0LyfQWJT6nXafLPZqxe9Of',
              },
            ],
            external_urls: {
              spotify: 'https://open.spotify.com/album/2pANdqPvxInB0YvcDiw4ko',
            },
            total_tracks: 20,
          },
          artists: [
            {
              external_urls: {
                spotify:
                  'https://open.spotify.com/artist/6eSdhw46riw2OUHgMwR8B5',
              },
              href: 'https://api.spotify.com/v1/artists/6eSdhw46riw2OUHgMwR8B5',
              id: '6eSdhw46riw2OUHgMwR8B5',
              name: 'Odiseo',
              type: 'artist',
              uri: 'spotify:artist:6eSdhw46riw2OUHgMwR8B5',
            },
          ],
          disc_number: 1,
          track_number: 10,
          duration_ms: 376000,
          external_ids: {
            isrc: 'DEKC41200989',
          },
          external_urls: {
            spotify: 'https://open.spotify.com/track/4rzfv0JLZfVhOhbSQ8o5jZ',
          },
          href: 'https://api.spotify.com/v1/tracks/4rzfv0JLZfVhOhbSQ8o5jZ',
          id: '4rzfv0JLZfVhOhbSQ8o5jZ',
          name: 'Api',
          popularity: 1,
          uri: 'spotify:track:4rzfv0JLZfVhOhbSQ8o5jZ',
          is_local: false,
        },
      },
      {
        added_at: '2015-01-15T12:40:03Z',
        added_by: {
          external_urls: {
            spotify: 'https://open.spotify.com/user/jmperezperez',
          },
          href: 'https://api.spotify.com/v1/users/jmperezperez',
          id: 'jmperezperez',
          type: 'user',
          uri: 'spotify:user:jmperezperez',
        },
        is_local: false,
        track: {
          preview_url:
            'https://p.scdn.co/mp3-preview/d61fbb7016904624373008ea056d45e6df891071?cid=cfe923b2d660439caf2b557b21f31221',
          available_markets: [],
          explicit: false,
          type: 'track',
          album: {
            available_markets: [],
            type: 'album',
            album_type: 'compilation',
            href: 'https://api.spotify.com/v1/albums/6nlfkk5GoXRL1nktlATNsy',
            id: '6nlfkk5GoXRL1nktlATNsy',
            images: [
              {
                height: 640,
                url: 'https://i.scdn.co/image/ab67616d0000b273aa2ff29970d9a63a49dfaeb2',
                width: 640,
              },
              {
                height: 300,
                url: 'https://i.scdn.co/image/ab67616d00001e02aa2ff29970d9a63a49dfaeb2',
                width: 300,
              },
              {
                height: 64,
                url: 'https://i.scdn.co/image/ab67616d00004851aa2ff29970d9a63a49dfaeb2',
                width: 64,
              },
            ],
            name: 'Wellness & Dreaming Source',
            release_date: '2015-01-09',
            release_date_precision: 'day',
            uri: 'spotify:album:6nlfkk5GoXRL1nktlATNsy',
            artists: [
              {
                external_urls: {
                  spotify:
                    'https://open.spotify.com/artist/0LyfQWJT6nXafLPZqxe9Of',
                },
                href: 'https://api.spotify.com/v1/artists/0LyfQWJT6nXafLPZqxe9Of',
                id: '0LyfQWJT6nXafLPZqxe9Of',
                name: 'Verschiedene Interpreten',
                type: 'artist',
                uri: 'spotify:artist:0LyfQWJT6nXafLPZqxe9Of',
              },
            ],
            external_urls: {
              spotify: 'https://open.spotify.com/album/6nlfkk5GoXRL1nktlATNsy',
            },
            total_tracks: 25,
          },
          artists: [
            {
              external_urls: {
                spotify:
                  'https://open.spotify.com/artist/5VQE4WOzPu9h3HnGLuBoA6',
              },
              href: 'https://api.spotify.com/v1/artists/5VQE4WOzPu9h3HnGLuBoA6',
              id: '5VQE4WOzPu9h3HnGLuBoA6',
              name: 'Vlasta Marek',
              type: 'artist',
              uri: 'spotify:artist:5VQE4WOzPu9h3HnGLuBoA6',
            },
          ],
          disc_number: 1,
          track_number: 21,
          duration_ms: 730066,
          external_ids: {
            isrc: 'FR2X41475057',
          },
          external_urls: {
            spotify: 'https://open.spotify.com/track/5o3jMYOSbaVz3tkgwhELSV',
          },
          href: 'https://api.spotify.com/v1/tracks/5o3jMYOSbaVz3tkgwhELSV',
          id: '5o3jMYOSbaVz3tkgwhELSV',
          name: 'Is',
          popularity: 0,
          uri: 'spotify:track:5o3jMYOSbaVz3tkgwhELSV',
          is_local: false,
        },
      },
      {
        added_at: '2015-01-15T12:22:30Z',
        added_by: {
          external_urls: {
            spotify: 'https://open.spotify.com/user/jmperezperez',
          },
          href: 'https://api.spotify.com/v1/users/jmperezperez',
          id: 'jmperezperez',
          type: 'user',
          uri: 'spotify:user:jmperezperez',
        },
        is_local: false,

        track: {
          preview_url:
            'https://p.scdn.co/mp3-preview/cc680ec0f5fd5ff21f0cd11ac47e10d3cbb92190?cid=cfe923b2d660439caf2b557b21f31221',
          available_markets: [
            'AR',
            'AU',
            'AT',
            'BE',
            'BO',
            'BR',
            'BG',
            'CA',
            'CL',
            'CO',
            'CR',
            'CY',
            'CZ',
            'DK',
            'DO',
            'DE',
            'EC',
            'EE',
            'SV',
            'FI',
            'FR',
            'GR',
            'GT',
            'HN',
            'HK',
            'HU',
            'IS',
            'IE',
            'IT',
            'LV',
            'LT',
            'LU',
            'MY',
            'MT',
            'MX',
            'NL',
            'NZ',
            'NI',
            'NO',
            'PA',
            'PY',
            'PE',
            'PH',
            'PL',
            'PT',
            'SG',
            'SK',
            'ES',
            'SE',
            'CH',
            'TW',
            'TR',
            'UY',
            'US',
            'GB',
            'AD',
            'LI',
            'MC',
            'ID',
            'JP',
            'TH',
            'VN',
            'RO',
            'IL',
            'ZA',
            'SA',
            'AE',
            'BH',
            'QA',
            'OM',
            'KW',
            'EG',
            'MA',
            'DZ',
            'TN',
            'LB',
            'JO',
            'PS',
            'IN',
            'BY',
            'KZ',
            'MD',
            'UA',
            'AL',
            'BA',
            'HR',
            'ME',
            'MK',
            'RS',
            'SI',
            'KR',
            'BD',
            'PK',
            'LK',
            'GH',
            'KE',
            'NG',
            'TZ',
            'UG',
            'AG',
            'AM',
            'BS',
            'BB',
            'BZ',
            'BT',
            'BW',
            'BF',
            'CV',
            'CW',
            'DM',
            'FJ',
            'GM',
            'GE',
            'GD',
            'GW',
            'GY',
            'HT',
            'JM',
            'KI',
            'LS',
            'LR',
            'MW',
            'MV',
            'ML',
            'MH',
            'FM',
            'NA',
            'NR',
            'NE',
            'PW',
            'PG',
            'PR',
            'WS',
            'SM',
            'ST',
            'SN',
            'SC',
            'SL',
            'SB',
            'KN',
            'LC',
            'VC',
            'SR',
            'TL',
            'TO',
            'TT',
            'TV',
            'VU',
            'AZ',
            'BN',
            'BI',
            'KH',
            'CM',
            'TD',
            'KM',
            'GQ',
            'SZ',
            'GA',
            'GN',
            'KG',
            'LA',
            'MO',
            'MR',
            'MN',
            'NP',
            'RW',
            'TG',
            'UZ',
            'ZW',
            'BJ',
            'MG',
            'MU',
            'MZ',
            'AO',
            'CI',
            'DJ',
            'ZM',
            'CD',
            'CG',
            'IQ',
            'LY',
            'TJ',
            'VE',
            'ET',
            'XK',
          ],
          explicit: false,
          type: 'track',
          album: {
            available_markets: [
              'AR',
              'AU',
              'AT',
              'BE',
              'BO',
              'BR',
              'BG',
              'CA',
              'CL',
              'CO',
              'CR',
              'CY',
              'CZ',
              'DK',
              'DO',
              'DE',
              'EC',
              'EE',
              'SV',
              'FI',
              'FR',
              'GR',
              'GT',
              'HN',
              'HK',
              'HU',
              'IS',
              'IE',
              'IT',
              'LV',
              'LT',
              'LU',
              'MY',
              'MT',
              'MX',
              'NL',
              'NZ',
              'NI',
              'NO',
              'PA',
              'PY',
              'PE',
              'PH',
              'PL',
              'PT',
              'SG',
              'SK',
              'ES',
              'SE',
              'CH',
              'TW',
              'TR',
              'UY',
              'US',
              'GB',
              'AD',
              'LI',
              'MC',
              'ID',
              'JP',
              'TH',
              'VN',
              'RO',
              'IL',
              'ZA',
              'SA',
              'AE',
              'BH',
              'QA',
              'OM',
              'KW',
              'EG',
              'MA',
              'DZ',
              'TN',
              'LB',
              'JO',
              'PS',
              'IN',
              'BY',
              'KZ',
              'MD',
              'UA',
              'AL',
              'BA',
              'HR',
              'ME',
              'MK',
              'RS',
              'SI',
              'KR',
              'BD',
              'PK',
              'LK',
              'GH',
              'KE',
              'NG',
              'TZ',
              'UG',
              'AG',
              'AM',
              'BS',
              'BB',
              'BZ',
              'BT',
              'BW',
              'BF',
              'CV',
              'CW',
              'DM',
              'FJ',
              'GM',
              'GE',
              'GD',
              'GW',
              'GY',
              'HT',
              'JM',
              'KI',
              'LS',
              'LR',
              'MW',
              'MV',
              'ML',
              'MH',
              'FM',
              'NA',
              'NR',
              'NE',
              'PW',
              'PG',
              'PR',
              'WS',
              'SM',
              'ST',
              'SN',
              'SC',
              'SL',
              'SB',
              'KN',
              'LC',
              'VC',
              'SR',
              'TL',
              'TO',
              'TT',
              'TV',
              'VU',
              'AZ',
              'BN',
              'BI',
              'KH',
              'CM',
              'TD',
              'KM',
              'GQ',
              'SZ',
              'GA',
              'GN',
              'KG',
              'LA',
              'MO',
              'MR',
              'MN',
              'NP',
              'RW',
              'TG',
              'UZ',
              'ZW',
              'BJ',
              'MG',
              'MU',
              'MZ',
              'AO',
              'CI',
              'DJ',
              'ZM',
              'CD',
              'CG',
              'IQ',
              'LY',
              'TJ',
              'VE',
              'ET',
              'XK',
            ],
            type: 'album',
            album_type: 'album',
            href: 'https://api.spotify.com/v1/albums/4hnqM0JK4CM1phwfq1Ldyz',
            id: '4hnqM0JK4CM1phwfq1Ldyz',
            images: [
              {
                height: 640,
                url: 'https://i.scdn.co/image/ab67616d0000b273ee0d0dce888c6c8a70db6e8b',
                width: 640,
              },
              {
                height: 300,
                url: 'https://i.scdn.co/image/ab67616d00001e02ee0d0dce888c6c8a70db6e8b',
                width: 300,
              },
              {
                height: 64,
                url: 'https://i.scdn.co/image/ab67616d00004851ee0d0dce888c6c8a70db6e8b',
                width: 64,
              },
            ],
            name: 'This Is Happening',
            release_date: '2010-05-17',
            release_date_precision: 'day',
            uri: 'spotify:album:4hnqM0JK4CM1phwfq1Ldyz',
            artists: [
              {
                external_urls: {
                  spotify:
                    'https://open.spotify.com/artist/066X20Nz7iquqkkCW6Jxy6',
                },
                href: 'https://api.spotify.com/v1/artists/066X20Nz7iquqkkCW6Jxy6',
                id: '066X20Nz7iquqkkCW6Jxy6',
                name: 'LCD Soundsystem',
                type: 'artist',
                uri: 'spotify:artist:066X20Nz7iquqkkCW6Jxy6',
              },
            ],
            external_urls: {
              spotify: 'https://open.spotify.com/album/4hnqM0JK4CM1phwfq1Ldyz',
            },
            total_tracks: 9,
          },
          artists: [
            {
              external_urls: {
                spotify:
                  'https://open.spotify.com/artist/066X20Nz7iquqkkCW6Jxy6',
              },
              href: 'https://api.spotify.com/v1/artists/066X20Nz7iquqkkCW6Jxy6',
              id: '066X20Nz7iquqkkCW6Jxy6',
              name: 'LCD Soundsystem',
              type: 'artist',
              uri: 'spotify:artist:066X20Nz7iquqkkCW6Jxy6',
            },
          ],
          disc_number: 1,
          track_number: 4,
          duration_ms: 401440,
          external_ids: {
            isrc: 'US4GE1000022',
          },
          external_urls: {
            spotify: 'https://open.spotify.com/track/4Cy0NHJ8Gh0xMdwyM9RkQm',
          },
          href: 'https://api.spotify.com/v1/tracks/4Cy0NHJ8Gh0xMdwyM9RkQm',
          id: '4Cy0NHJ8Gh0xMdwyM9RkQm',
          name: 'All I Want',
          popularity: 42,
          uri: 'spotify:track:4Cy0NHJ8Gh0xMdwyM9RkQm',
          is_local: false,
        },
      },
      {
        added_at: '2015-01-15T12:40:35Z',
        added_by: {
          external_urls: {
            spotify: 'https://open.spotify.com/user/jmperezperez',
          },
          href: 'https://api.spotify.com/v1/users/jmperezperez',
          id: 'jmperezperez',
          type: 'user',
          uri: 'spotify:user:jmperezperez',
        },
        is_local: false,
        track: {
          preview_url:
            'https://p.scdn.co/mp3-preview/d6ecf1f98d0b1fdc8c535de8e2010d0d8b8d040b?cid=cfe923b2d660439caf2b557b21f31221',
          available_markets: [
            'AR',
            'AU',
            'AT',
            'BE',
            'BO',
            'BR',
            'BG',
            'CA',
            'CL',
            'CO',
            'CR',
            'CY',
            'CZ',
            'DK',
            'DO',
            'DE',
            'EC',
            'EE',
            'SV',
            'FI',
            'FR',
            'GR',
            'GT',
            'HN',
            'HK',
            'HU',
            'IS',
            'IE',
            'IT',
            'LV',
            'LT',
            'LU',
            'MY',
            'MT',
            'MX',
            'NL',
            'NZ',
            'NI',
            'NO',
            'PA',
            'PY',
            'PE',
            'PH',
            'PL',
            'PT',
            'SG',
            'SK',
            'ES',
            'SE',
            'CH',
            'TW',
            'TR',
            'UY',
            'US',
            'GB',
            'AD',
            'LI',
            'MC',
            'ID',
            'JP',
            'TH',
            'VN',
            'RO',
            'IL',
            'ZA',
            'SA',
            'AE',
            'BH',
            'QA',
            'OM',
            'KW',
            'EG',
            'MA',
            'DZ',
            'TN',
            'LB',
            'JO',
            'PS',
            'IN',
            'BY',
            'KZ',
            'MD',
            'UA',
            'AL',
            'BA',
            'HR',
            'ME',
            'MK',
            'RS',
            'SI',
            'KR',
            'BD',
            'PK',
            'LK',
            'GH',
            'KE',
            'NG',
            'TZ',
            'UG',
            'AG',
            'AM',
            'BS',
            'BB',
            'BZ',
            'BT',
            'BW',
            'BF',
            'CV',
            'CW',
            'DM',
            'FJ',
            'GM',
            'GE',
            'GD',
            'GW',
            'GY',
            'HT',
            'JM',
            'KI',
            'LS',
            'LR',
            'MW',
            'MV',
            'ML',
            'MH',
            'FM',
            'NA',
            'NR',
            'NE',
            'PW',
            'PG',
            'PR',
            'WS',
            'SM',
            'ST',
            'SN',
            'SC',
            'SL',
            'SB',
            'KN',
            'LC',
            'VC',
            'SR',
            'TL',
            'TO',
            'TT',
            'TV',
            'VU',
            'AZ',
            'BN',
            'BI',
            'KH',
            'CM',
            'TD',
            'KM',
            'GQ',
            'SZ',
            'GA',
            'GN',
            'KG',
            'LA',
            'MO',
            'MR',
            'MN',
            'NP',
            'RW',
            'TG',
            'UZ',
            'ZW',
            'BJ',
            'MG',
            'MU',
            'MZ',
            'AO',
            'CI',
            'DJ',
            'ZM',
            'CD',
            'CG',
            'IQ',
            'LY',
            'TJ',
            'VE',
            'ET',
            'XK',
          ],
          explicit: false,
          type: 'track',
          album: {
            available_markets: [
              'AR',
              'AU',
              'AT',
              'BE',
              'BO',
              'BR',
              'BG',
              'CA',
              'CL',
              'CO',
              'CR',
              'CY',
              'CZ',
              'DK',
              'DO',
              'DE',
              'EC',
              'EE',
              'SV',
              'FI',
              'FR',
              'GR',
              'GT',
              'HN',
              'HK',
              'HU',
              'IS',
              'IE',
              'IT',
              'LV',
              'LT',
              'LU',
              'MY',
              'MT',
              'MX',
              'NL',
              'NZ',
              'NI',
              'NO',
              'PA',
              'PY',
              'PE',
              'PH',
              'PL',
              'PT',
              'SG',
              'SK',
              'ES',
              'SE',
              'CH',
              'TW',
              'TR',
              'UY',
              'US',
              'GB',
              'AD',
              'LI',
              'MC',
              'ID',
              'JP',
              'TH',
              'VN',
              'RO',
              'IL',
              'ZA',
              'SA',
              'AE',
              'BH',
              'QA',
              'OM',
              'KW',
              'EG',
              'MA',
              'DZ',
              'TN',
              'LB',
              'JO',
              'PS',
              'IN',
              'BY',
              'KZ',
              'MD',
              'UA',
              'AL',
              'BA',
              'HR',
              'ME',
              'MK',
              'RS',
              'SI',
              'KR',
              'BD',
              'PK',
              'LK',
              'GH',
              'KE',
              'NG',
              'TZ',
              'UG',
              'AG',
              'AM',
              'BS',
              'BB',
              'BZ',
              'BT',
              'BW',
              'BF',
              'CV',
              'CW',
              'DM',
              'FJ',
              'GM',
              'GE',
              'GD',
              'GW',
              'GY',
              'HT',
              'JM',
              'KI',
              'LS',
              'LR',
              'MW',
              'MV',
              'ML',
              'MH',
              'FM',
              'NA',
              'NR',
              'NE',
              'PW',
              'PG',
              'PR',
              'WS',
              'SM',
              'ST',
              'SN',
              'SC',
              'SL',
              'SB',
              'KN',
              'LC',
              'VC',
              'SR',
              'TL',
              'TO',
              'TT',
              'TV',
              'VU',
              'AZ',
              'BN',
              'BI',
              'KH',
              'CM',
              'TD',
              'KM',
              'GQ',
              'SZ',
              'GA',
              'GN',
              'KG',
              'LA',
              'MO',
              'MR',
              'MN',
              'NP',
              'RW',
              'TG',
              'UZ',
              'ZW',
              'BJ',
              'MG',
              'MU',
              'MZ',
              'AO',
              'CI',
              'DJ',
              'ZM',
              'CD',
              'CG',
              'IQ',
              'LY',
              'TJ',
              'VE',
              'ET',
              'XK',
            ],
            type: 'album',
            album_type: 'album',
            href: 'https://api.spotify.com/v1/albums/2usKFntxa98WHMcyW6xJBz',
            id: '2usKFntxa98WHMcyW6xJBz',
            images: [
              {
                height: 640,
                url: 'https://i.scdn.co/image/ab67616d0000b2738b7447ac3daa1da18811cf7b',
                width: 640,
              },
              {
                height: 300,
                url: 'https://i.scdn.co/image/ab67616d00001e028b7447ac3daa1da18811cf7b',
                width: 300,
              },
              {
                height: 64,
                url: 'https://i.scdn.co/image/ab67616d000048518b7447ac3daa1da18811cf7b',
                width: 64,
              },
            ],
            name: 'Glenn Horiuchi Trio / Gelenn Horiuchi Quartet: Mercy / Jump Start / Endpoints / Curl Out / Earthworks / Mind Probe / Null Set / Another Space (A)',
            release_date: '2011-04-01',
            release_date_precision: 'day',
            uri: 'spotify:album:2usKFntxa98WHMcyW6xJBz',
            artists: [
              {
                external_urls: {
                  spotify:
                    'https://open.spotify.com/artist/272ArH9SUAlslQqsSgPJA2',
                },
                href: 'https://api.spotify.com/v1/artists/272ArH9SUAlslQqsSgPJA2',
                id: '272ArH9SUAlslQqsSgPJA2',
                name: 'Glenn Horiuchi Trio',
                type: 'artist',
                uri: 'spotify:artist:272ArH9SUAlslQqsSgPJA2',
              },
            ],
            external_urls: {
              spotify: 'https://open.spotify.com/album/2usKFntxa98WHMcyW6xJBz',
            },
            total_tracks: 8,
          },
          artists: [
            {
              external_urls: {
                spotify:
                  'https://open.spotify.com/artist/272ArH9SUAlslQqsSgPJA2',
              },
              href: 'https://api.spotify.com/v1/artists/272ArH9SUAlslQqsSgPJA2',
              id: '272ArH9SUAlslQqsSgPJA2',
              name: 'Glenn Horiuchi Trio',
              type: 'artist',
              uri: 'spotify:artist:272ArH9SUAlslQqsSgPJA2',
            },
          ],
          disc_number: 1,
          track_number: 2,
          duration_ms: 358760,
          external_ids: {
            isrc: 'USB8U1025969',
          },
          external_urls: {
            spotify: 'https://open.spotify.com/track/6hvFrZNocdt2FcKGCSY5NI',
          },
          href: 'https://api.spotify.com/v1/tracks/6hvFrZNocdt2FcKGCSY5NI',
          id: '6hvFrZNocdt2FcKGCSY5NI',
          name: 'Endpoints',
          popularity: 0,
          uri: 'spotify:track:6hvFrZNocdt2FcKGCSY5NI',
          is_local: false,
        },
      },
      {
        added_at: '2015-01-15T12:41:10Z',
        added_by: {
          external_urls: {
            spotify: 'https://open.spotify.com/user/jmperezperez',
          },
          href: 'https://api.spotify.com/v1/users/jmperezperez',
          id: 'jmperezperez',
          type: 'user',
          uri: 'spotify:user:jmperezperez',
        },
        is_local: false,
        track: {
          preview_url: null,
          available_markets: [],
          explicit: false,
          type: 'track',
          album: {
            available_markets: [],
            type: 'album',
            album_type: 'album',
            href: 'https://api.spotify.com/v1/albums/0ivM6kSawaug0j3tZVusG2',
            id: '0ivM6kSawaug0j3tZVusG2',
            images: [
              {
                height: 640,
                url: 'https://i.scdn.co/image/ab67616d0000b27304e57d181ff062f8339d6c71',
                width: 640,
              },
              {
                height: 300,
                url: 'https://i.scdn.co/image/ab67616d00001e0204e57d181ff062f8339d6c71',
                width: 300,
              },
              {
                height: 64,
                url: 'https://i.scdn.co/image/ab67616d0000485104e57d181ff062f8339d6c71',
                width: 64,
              },
            ],
            name: 'All The Best (Spanish Version)',
            release_date: '2007-01-01',
            release_date_precision: 'day',
            uri: 'spotify:album:0ivM6kSawaug0j3tZVusG2',
            artists: [
              {
                external_urls: {
                  spotify:
                    'https://open.spotify.com/artist/2KftmGt9sk1yLjsAoloC3M',
                },
                href: 'https://api.spotify.com/v1/artists/2KftmGt9sk1yLjsAoloC3M',
                id: '2KftmGt9sk1yLjsAoloC3M',
                name: 'Zucchero',
                type: 'artist',
                uri: 'spotify:artist:2KftmGt9sk1yLjsAoloC3M',
              },
            ],
            external_urls: {
              spotify: 'https://open.spotify.com/album/0ivM6kSawaug0j3tZVusG2',
            },
            total_tracks: 18,
          },
          artists: [
            {
              external_urls: {
                spotify:
                  'https://open.spotify.com/artist/2KftmGt9sk1yLjsAoloC3M',
              },
              href: 'https://api.spotify.com/v1/artists/2KftmGt9sk1yLjsAoloC3M',
              id: '2KftmGt9sk1yLjsAoloC3M',
              name: 'Zucchero',
              type: 'artist',
              uri: 'spotify:artist:2KftmGt9sk1yLjsAoloC3M',
            },
          ],
          disc_number: 1,
          track_number: 18,
          duration_ms: 176093,
          external_ids: {
            isrc: 'ITUM70701043',
          },
          external_urls: {
            spotify: 'https://open.spotify.com/track/2E2znCPaS8anQe21GLxcvJ',
          },
          href: 'https://api.spotify.com/v1/tracks/2E2znCPaS8anQe21GLxcvJ',
          id: '2E2znCPaS8anQe21GLxcvJ',
          name: 'You Are So Beautiful',
          popularity: 0,
          uri: 'spotify:track:2E2znCPaS8anQe21GLxcvJ',
          is_local: false,
        },
      },
    ],
    limit: 100,
    next: null,
    offset: 0,
    previous: null,
    total: 5,
  };
